version: '3.8'

volumes:
  postgis_vol:
  geoserver_vol:

services:
  postgis:
    # Database to store all geospatial data
    image: postgis/postgis
    container_name: postgis_carbon_neutral
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgis_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -h 127.0.0.1 -U $POSTGRES_USER -d $POSTGRES_DB

  geoserver:
    # Serves geospatial web data through interactions with files and database
    image: docker.osgeo.org/geoserver:2.21.2
    container_name: geoserver_carbon_neutral
    volumes:
      - geoserver_vol:/opt/geoserver_data
    depends_on:
      - postgis
    environment:
      - SKIP_DEMO_DATA=true
      - CORS_ENABLED=true
    ports:
      - "${GEOSERVER_PORT}:8080"
    restart: always
    healthcheck:
      test: curl --fail -s http://localhost:8080/geoserver || exit 1
      interval: 5s
      timeout: 3s
      retries: 5

  www:
    # Webserver to visualise and interact with the data
    build:
      context: ./www
    container_name: www_digital_twin
    environment:
      - VUE_APP_CESIUM_ACCESS_TOKEN=$CESIUM_ACCESS_TOKEN
      - VUE_APP_GEOSERVER_HOST=$GEOSERVER_HOST
      - VUE_APP_GEOSERVER_PORT=$GEOSERVER_PORT
    ports:
      - "${WWW_PORT}:80"
    restart: always

  initialise_db:
    build:
      context: initialise_db
    container_name: initialise_db_carbon_neutral
    volumes:
    - "./initialise_db/data:/app/data"
    env_file:
      - .env
      - .env.docker-override
    depends_on:
      postgis:
        condition: service_healthy
      geoserver:
        condition: service_healthy
